### ISSUE TITLE
Code generated for XGBoost models return error scores when feature input include zero which result in  xgboost "missing" 

### ISSUE THREAD

**Issue by crystaldan** [BayesWitnesses/m2cgen#187] opened 2020-03-27 12:08 UTC
I’m try using m2cgen to generate js code for XGBoost model，but find that if the feature input include zero，the result which calculate by generated js has a big difference with the result which predicted by model. For example, if the feature input is [0.4444,0.55555,0.3545,0.22333]，the result which calculate by generated js equals  the result which predicted by model，but if the feature input is [0.4444,0,0,0.22333]，the result which calculate by generated js will be very different from   the result which predicted by model,maybe one result is 0.22 ,the other one result is 0.04。After we validate by demo，we find that m2cgen not process “missing” condition.  when xgboost result in “missing”, m2cgen will process it as “yes”

**Comment by izeigerman** [comment] 2020-03-27 20:52
@crystaldan thanks for reporting the issue. 

Can you please provide some steps to reproduce. If I recall the notion of the "missing" value in XGBoost correctly, then zero - is not a missing value, zero is just zero value. "Missing" value are NaNs. Am I wrong here?

Are you sure you're not hitting the other XGBoost issue - https://github.com/BayesWitnesses/m2cgen/issues/168 ?

Thanks.

**Comment by izeigerman** [comment] 2020-04-07 16:49
Closing this due to the lack of details and in a hope that this is a duplicate of https://github.com/BayesWitnesses/m2cgen/issues/168. @crystaldan please feel free to reopen this if the problem persists in version `0.7.0` and onward.

**Closed by izeigerman** 2020-04-07 16:49 UTC
