### ISSUE TITLE
convert lightgbm gbdt bug

### ISSUE THREAD

**Issue by gnodabb** [BayesWitnesses/m2cgen#90] opened 2019-05-15 12:21 UTC
Model Booster is not supported error. When using a light gbm model trained with 'gbdt'. export function fails with model not supported error. Below is snippet code.

```
import os
import h5py

import lightgbm as lgb
import numpy as np
import m2cgen as m2c

with h5py.File('./sample.hdf5') as f:
    X, y = f['X'][()], f['y'][()]

dtrain=lgb.Dataset(X[:1000,:],label=y[:1000])

param = {
    'boosting_type': 'gbdt',
    'objective': 'binary',
    'num_leaves':2**4,
    'max_depth': 4, 
    'learning_rate': 0.1,
    'verbose': 0}
n_estimators = 5

bst = lgb.train(param, dtrain, n_estimators)
code = m2c.export_to_c(bst)
```

Additionally, here is the error output:
```
---------------------------------------------------------------------------
NotImplementedError                       Traceback (most recent call last)
<ipython-input-5-226faacde9f0> in <module>
----> 1 code = m2c.export_to_java(bst)
      2 print(code)

C:\ProgramData\Anaconda3\envs\light_gbm\lib\site-packages\m2cgen\exporters.py in export_to_java(model, package_name, class_name, indent)
     26         class_name=class_name,
     27         indent=indent)
---> 28     return _export(model, interpreter)
     29 
     30 

C:\ProgramData\Anaconda3\envs\light_gbm\lib\site-packages\m2cgen\exporters.py in _export(model, interpreter)
     87 
     88 def _export(model, interpreter):
---> 89     assembler_cls = assemblers.get_assembler_cls(model)
     90     model_ast = assembler_cls(model).assemble()
     91     return interpreter.interpret(model_ast)

C:\ProgramData\Anaconda3\envs\light_gbm\lib\site-packages\m2cgen\assemblers\__init__.py in get_assembler_cls(model)
     74     if not assembler_cls:
     75         raise NotImplementedError(
---> 76             "Model {} is not supported".format(model_name))
     77 
     78     return assembler_cls

NotImplementedError: Model Booster is not supported
```

**Comment by izeigerman** [comment] 2019-05-15 15:57
Hi @gnodabb ! Thanks for reporting this issue. This is expected behavior, since `m2cgen` expects the `sklearn` wrapper to be passed instead of a booster object. The corresponding wrappers are: `lightgbm.LGBMRegressor` and `lightgbm.LGBMRegressor` for regression and classification accordingly. Can you try passing them instead?

**Comment by gnodabb** [comment] 2019-05-15 19:35
Gotcha! Thank you! Sorry for the inconvenience. Awesome tool!

**Comment by izeigerman** [comment] 2019-05-15 19:53
@gnodabb no problem at all, I'm glad my suggestion helped. Happy to hear that you enjoy using `m2cgen`! Closing the issue now.

**Closed by izeigerman** 2019-05-15 19:53 UTC
