### ISSUE TITLE
when i try to export svc model to c, it takes a long time and without responding

### ISSUE THREAD

**Issue by ArtemisZGL** [BayesWitnesses/m2cgen#112] opened 2019-10-20 09:32 UTC
compared to export xgboost, when i try to export the sklearn svc model, it takes so long, and doesn't show any error or infomation, i dont know how long should i wait for that

**Comment by izeigerman** [comment] 2019-10-22 15:25
Hi @ArtemisZGL! Thanks for reporting this! Can you please provide some steps to reproduce this issue? Ideally with some publicly available dataset or with some dataset from `scikit-learn` library?

**Comment by izeigerman** [comment] 2019-12-01 18:39
Closing this due to inability to reproduce the issue.

**Closed by izeigerman** 2019-12-01 18:39 UTC
